### ISSUE TITLE
Workflow Authorization 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/workflow-management#4]
- [x] Uses API key ( from https://platform-ui.qa.argo.cancercollaboratory.org/user / https://ego.qa.argo.cancercollaboratory.org/api/swagger-ui.html#/token-controller ) 
- [x] Define the permission/scopes needed to user/run workflows.  Should be similar to Song/Score 
- [x] Only RDPC members can access/run workflow information

**Comment by akachru-github** [comment]
Requires design meeting.

**Comment by andricDu** [comment]
This issue is now stale and most of it has been handled or the designed already.
